version: "3.9"

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  app:
    build: .
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on: [redis]
    ports: ["3000:3000"]
    volumes: [".:/app"]
